#!/usr/bin/zsh

exec > "/home/alli/bin/cb_out"

WORKING_DIR="/home/alli/media/pics/backgrounds/image"

# check internet connection
ping -c 1 -W 2 google.com
if [[ "$?" != "0" ]]; then
    echo "No internet connection"
    exit 1
fi

# call python program with like/dislike variable ($1, specificed in i3 config)
# and filename of image
cd $WORKING_DIR
IMAGE_NAME=$(ls | grep -v '\.txt')
echo "Found old image," $IMAGE_NAME
echo "Generating new search"
python -m search_generator $1 $IMAGE_NAME

# if download fails, run script again - will generate new random search
# trying twice catches a majority of the times it fails to download
if [[ "$?" != 0 ]]; then
    python -m search_generator $1 $IMAGE_NAME
    # exit out if it still fails
    if [[ "$?" != 0 ]]; then
        exit -1
    fi
fi

# check that the python program successfully downloaded another image
# depends on no other files being stored in this directory
if [[ $(ls -1 | wc -l) == "3" ]]; then
    rm $IMAGE_NAME
    IMAGE_NAME=$(ls | grep -v '\.txt')
    echo "Found new image," $IMAGE_NAME

    feh  --bg-scale $IMAGE_NAME
    # if feh fails, image was in wrong format, will have to manually run search again
fi

